export const accountReliabilityMessages = {
  en: {
    flexibilityLevels: ["Very limited", "Limited", "Average", "Good", "Excellent"],
    coreLevels: ["Plank < 20 s", "Plank 20-40 s", "Plank 40-60 s", "Plank 60-90 s", "Plank > 90 s"],
    scoreUnknown: "Not entered",
    loadError: "We could not load your measurements. Please try again.",
    saddle: "Saddle height", knee: "Measure your knee angle", inseam: "Inseam", updated: "Last saved", kneeProjection: "Possible range after a measured knee angle within 25–35°", intro: "We use the values in your profile. Review them and save your changes.",
    loading: "Loading your measurements…", signIn: "Sign in to use your saved measurements.", empty: "Add your height and inseam to your profile to get started.", profile: "Open your profile", error: "We could not save your changes. Your input is still here; please try again.", saved: "Saved", saving: "Saving…", save: "Save changes", retry: "Try again",
    measurements: "1. Inseam measurements", newMeasurement: "New measurement (cm)", saveMeasurement: "Save measurement", noMeasurements: "No repeat measurements saved yet.", fromProfile: "From your profile", measured: "Measured", estimated: "Estimated", declared: "Self-reported", derived: "Calculated", unknownDate: "Date not recorded", basis: "Based on", mean: "Mean", spread: "These measurements differ by more than 5 mm. Measure again; they only count as repeat measurements when they agree.",
    measureHelp: "Barefoot, stand against a wall. Hold a book firmly up between your legs and measure from the floor to its top. Step away and repeat independently.", invalid: "Enter a value between 55 and 105 cm, shorter than your height.", check: "Your inseam differs from the average for your height. Check that you measured in centimetres and held the book firmly upwards.", large: "This inseam differs strongly from the value expected for your height. Measure again or ask a qualified bike fitter. Using it keeps the wider uncertainty range.", confirm: "Correct, continue", override: "Use anyway", remeasure: "Measure again", fitter: "Find a bike fitter", unresolved: "Measurement needs checking; the uncertainty range remains wider.",
    bikeGoal: "2. Your bike and riding goal", bike: "Bike type", goal: "Riding goal", road: "Road", gravel: "Gravel", mtb: "Mountain bike", city: "City", comfort: "Comfort", balanced: "Balanced", performance: "Performance", aero: "Aero", choose: "Choose…", selectBike: "Your bike", noBike: "General profile",
    assessments: "3. Flexibility and core", selfAssessed: "Self-assessed", flexibility: "Flexibility", core: "Core stability", assessmentHelp: "These estimates shift the advice by a few millimetres; they do not narrow the range.", climbing: "Climbing", low: "Little", medium: "Some", high: "Frequent", veryHigh: "Very frequent", current: "Current saddle height (mm)",
    advice: "Your advice", reference: "Bottom bracket centre to saddle top, along the seat tube", breakdown: "How we arrive at", base: "Inseam × bike factor", total: "Advice", difference: "Difference from your current setting", repeatNext: "Measure your inseam again to refine the range.", chooseNext: "Choose your bike and riding goal to personalise the advice.", narrowest: "This is the narrowest range we can currently give online.", teaser: "Go further: check your knee angle", teaserBody: "Your three measurements agree. Take a side-on photo and measure the angle yourself to refine your advice and make an adjustment plan.", kneeLink: "Check your knee angle", safety: "Pain or tingling? Stop adjusting and consult a qualified bike fitter or physiotherapist.",
    comingSoon: "Coming soon: we measure the angle from your photo", photoCaption: "Measure the angle between the extension of your thigh (dashed line) and your lower leg.", hip: "Hip", kneeJoint: "Knee", ankle: "Ankle", angle: "Angle", instructions: "How to measure", steps: ["Put your bike on a trainer or ask someone to hold it. Wear your cycling shoes.", "Pedal gently, then stop with the crank aligned with the seat tube and the pedal at the bottom.", "Ask someone to take a photo directly from the side, at hip height.", "Use a protractor app or a printed photo. Measure twice and enter the average, not the internal angle of the knee."],
    angleInput: "Measured knee angle (°)", angleHelp: "Enter the average of two measurements, between 15° and 45°.", saveAngle: "Save knee angle and plan", angleInvalid: "Enter an angle from 15° to 45° and your current saddle height.", inWindow: "Within the recommended 25–35° window.", tooStraight: "Below 25°: your leg is too straight; the saddle is probably too high.", tooBent: "Above 35°: your knee is too bent; the saddle is probably too low.", photoMeasured: "Self-measured from a photo", plan: "Your adjustment plan", keep: "Keep your saddle at", raise: "Raise your saddle by", lower: "Lower your saddle by", target: "Target for this step", rides: "Take two easy rides of at least one hour.", evaluate: "After 7 days, evaluate your knees, lower back and any rocking on the saddle. Email reminders follow your email preferences.", due: "Evaluation date", recheck: "Measure your knee angle again before any next step; adjust by no more than 5 mm per step.", nextPart: "Then continue with saddle setback.", locked: "Knee-angle checking requires paid access for this bike.", pricing: "View plans", needMeasurements: "Save your profile measurements before checking your knee angle.", noAngle: "No knee-angle measurement saved yet. Follow the steps and enter your measured angle.",
  },
  nl: {
    flexibilityLevels: ["Zeer beperkt", "Beperkt", "Gemiddeld", "Goed", "Uitstekend"],
    coreLevels: ["Plank < 20 s", "Plank 20-40 s", "Plank 40-60 s", "Plank 60-90 s", "Plank > 90 s"],
    scoreUnknown: "Niet ingevuld",
    loadError: "We konden je metingen niet laden. Probeer het opnieuw.",
    saddle: "Zadelhoogte", knee: "Meet je kniehoek", inseam: "Binnenbeen", updated: "Laatst bewaard", kneeProjection: "Mogelijk bereik na een gemeten kniehoek binnen 25–35°", intro: "We gebruiken wat in je profiel staat. Controleer de waarden en bewaar je wijzigingen.",
    loading: "Je metingen laden…", signIn: "Log in om je bewaarde metingen te gebruiken.", empty: "Vul je lengte en binnenbeen in je profiel in om te beginnen.", profile: "Open je profiel", error: "We konden je wijzigingen niet bewaren. Je invoer staat er nog; probeer het opnieuw.", saved: "Bewaard", saving: "Bewaren…", save: "Wijzigingen bewaren", retry: "Opnieuw proberen",
    measurements: "1. Binnenbeenmetingen", newMeasurement: "Nieuwe meting (cm)", saveMeasurement: "Meting bewaren", noMeasurements: "Nog geen herhaalmetingen bewaard.", fromProfile: "Uit je profiel", measured: "Gemeten", estimated: "Geschat", declared: "Zelf opgegeven", derived: "Berekend", unknownDate: "Datum niet vastgelegd", basis: "Gebaseerd op", mean: "Gemiddeld", spread: "De metingen liggen meer dan 5 mm uit elkaar. Meet opnieuw; ze tellen pas als herhaalde meting als ze dicht bij elkaar liggen.",
    measureHelp: "Ga blootsvoets tegen een muur staan. Houd een boek stevig omhoog tussen je benen en meet van de vloer tot de bovenkant. Stap weg en herhaal de meting onafhankelijk.", invalid: "Vul een waarde tussen 55 en 105 cm in, korter dan je lengte.", check: "Je binnenbeen wijkt af van het gemiddelde bij jouw lengte. Controleer of je in centimeters hebt gemeten en het boek stevig omhoog hield.", large: "Deze binnenbeenlengte wijkt sterk af van wat we bij jouw lengte verwachten. Meet opnieuw of laat je meten door een erkende bikefitter. Bij gebruik blijft het bereik breder.", confirm: "Klopt, ga verder", override: "Toch gebruiken", remeasure: "Opnieuw meten", fitter: "Vind een bikefitter", unresolved: "Controleer deze meting; het onzekerheidsbereik blijft breder.",
    bikeGoal: "2. Je fiets en rijdoel", bike: "Fietstype", goal: "Rijdoel", road: "Race", gravel: "Gravel", mtb: "Mountainbike", city: "Stad", comfort: "Comfort", balanced: "Gebalanceerd", performance: "Prestatie", aero: "Aero", choose: "Kies…", selectBike: "Je fiets", noBike: "Algemeen profiel",
    assessments: "3. Lenigheid en core", selfAssessed: "Zelf ingeschat", flexibility: "Lenigheid", core: "Core-stabiliteit", assessmentHelp: "Deze inschattingen verschuiven je advies een paar millimeter; ze maken het bereik niet smaller.", climbing: "Klimmen", low: "Weinig", medium: "Soms", high: "Vaak", veryHigh: "Heel vaak", current: "Huidige zadelhoogte (mm)",
    advice: "Jouw advies", reference: "Midden trapas tot bovenkant zadel, langs de zitbuis", breakdown: "Hoe we komen op", base: "Binnenbeen × fietsfactor", total: "Advies", difference: "Verschil met je huidige afstelling", repeatNext: "Meet je binnenbeen opnieuw om het bereik te verfijnen.", chooseNext: "Kies je fiets en rijdoel; je advies past zich aan.", narrowest: "Dit is het smalste bereik dat we nu online kunnen geven.", teaser: "Verdieping: controleer je kniehoek", teaserBody: "Je drie metingen komen overeen. Maak een foto van opzij en meet zelf de hoek om je advies te verfijnen en een aanpassingsplan te maken.", kneeLink: "Controleer je kniehoek", safety: "Pijn of tintelingen? Stop met aanpassen en ga naar een erkende bikefitter of fysiotherapeut.",
    comingSoon: "Binnenkort: wij meten de hoek uit je foto", photoCaption: "Meet de hoek tussen het verlengde van je bovenbeen (stippellijn) en je onderbeen.", hip: "Heup", kneeJoint: "Knie", ankle: "Enkel", angle: "Hoek", instructions: "Zo meet je het", steps: ["Zet je fiets op een trainer of laat iemand hem vasthouden. Draag je fietsschoenen.", "Trap rustig en stop met de crank in het verlengde van de zitbuis, pedaal onderaan.", "Laat iemand een foto maken recht van opzij, op heuphoogte.", "Meet met een gradenboog-app of op een print. Meet twee keer en vul het gemiddelde in, niet de binnenhoek van de knie."],
    angleInput: "Gemeten kniehoek (°)", angleHelp: "Vul het gemiddelde van twee metingen in, tussen 15° en 45°.", saveAngle: "Kniehoek en plan bewaren", angleInvalid: "Vul een hoek van 15° tot 45° en je huidige zadelhoogte in.", inWindow: "Binnen het aanbevolen venster van 25–35°.", tooStraight: "Onder 25°: je been is te gestrekt; je zadel staat waarschijnlijk te hoog.", tooBent: "Boven 35°: je knie is te gebogen; je zadel staat waarschijnlijk te laag.", photoMeasured: "Zelf gemeten op een foto", plan: "Je aanpassingsplan", keep: "Laat je zadel staan op", raise: "Zet je zadel hoger met", lower: "Zet je zadel lager met", target: "Doel voor deze stap", rides: "Rijd twee rustige ritten van minstens een uur.", evaluate: "Evalueer na 7 dagen je knieën, onderrug en wiegen op het zadel. Herinneringen per mail volgen je e-mailvoorkeuren.", due: "Evaluatiedatum", recheck: "Meet je kniehoek opnieuw voor een volgende stap; verstel maximaal 5 mm per stap.", nextPart: "Ga daarna verder met zadelterugstand.", locked: "Voor de kniehoekcontrole heb je betaalde toegang voor deze fiets nodig.", pricing: "Bekijk abonnementen", needMeasurements: "Bewaar je profielmetingen voordat je je kniehoek controleert.", noAngle: "Nog geen kniehoekmeting bewaard. Volg de stappen en vul je gemeten hoek in.",
  },
};

export type AccountReliabilityCopy = (typeof accountReliabilityMessages)["en"];
