import type { Locale } from "@/i18n/config";

const nl = {
  welcome: "Welkom", title: "Dit nemen we mee", step: "Stap 1 van 2 · je account staat klaar",
  intro: "Uit de calculators die je net gebruikte. Kies per gegeven of het in je profiel komt; je kunt alles later aanpassen.",
  rider: "Naar je riderprofiel", riderHint: "over jou, voor elke fiets", bike: "Naar een nieuw fietsprofiel", bikeHint: "alleen voor deze fiets",
  keep: "Bewaren", omit: "Weglaten", adjust: "Pas aan", createBike: "Maak fietsprofiel", later: "Later", bikeName: "Naam van je fiets", bikeType: "Type fiets", choose: "Kies een optie",
  measurePoint: "Meetpunt zadelhoogte", measurePointOption: "Midden trapas tot bovenkant zadel", measurePointHint: "Bevestig hoe je de huidige zadelhoogte hebt gemeten voordat je deze bewaart.",
  confirm: "Bewaar en ga naar mijn dashboard", cancel: "Niets meenemen, leeg beginnen", loading: "Je gegevens laden…", saving: "Gegevens bewaren…",
  empty: "Er staan geen calculatorgegevens klaar. Je kunt verdergaan en je profiel later aanvullen.", error: "Bewaren is niet gelukt. Je gegevens blijven klaarstaan. Controleer je invoer en probeer opnieuw.",
  conflict: "Je profiel heeft al een andere waarde", profileValue: "Je profiel", incomingValue: "Vandaag", profile: "Uit mijn profiel", today: "Van vandaag", remeasure: "Ik meet opnieuw", remeasureHint: "De huidige profielwaarde blijft staan. Meet opnieuw en pas je profiel later aan.",
  start: "Zo start je", riderScore: "Riderprofiel", bikeScore: "Fietsprofiel", scoreHint: "Elk gegeven dat je toevoegt maakt je advies persoonlijker. We vragen er bij elk bezoek hooguit twee.",
  first: "Eerste vraag", gain: "+8 volledig", question: "Hoe ver kom je met gestrekte benen?", flexHint: "Je drop-advies houdt rekening met je flexibiliteit. Je mag deze vraag overslaan.", flexKept: "Klaar om te bewaren als zelf ingeschat. Bevestig hieronder je gegevens.",
  methods: { measured: "Gemeten", estimated: "Geschat", declared: "Opgegeven", bike: "Fietsgegeven" },
  extraValues: { known: "Ik ken mijn FTP", twentyMinute: "Twintigminutentest", medium: "Gemiddeld", smooth_asphalt: "Glad asfalt", average_asphalt: "Gemiddeld asfalt", rough_asphalt: "Ruw asfalt", hardpack_gravel: "Hard gravel", loose_gravel: "Los gravel" },
  fields: { heightCm: "Lichaamslengte", inseamCm: "Binnenbeenlengte", flexibilityScore: "Flexibiliteit", coreStabilityScore: "Rompstabiliteit", ridingGoal: "Standaard rijdoel", weightKg: "Gewicht", ftpWatts: "FTP", ftpMethod: "FTP-methode", sitBoneWidthMm: "Zitbotbreedte", sweatProfile: "Zweetprofiel", bikeCategory: "Type fiets", currentSaddleHeightMm: "Huidige zadelhoogte", currentCrankLengthMm: "Huidige cranklengte", currentSaddleWidthMm: "Huidige zadelbreedte", currentSaddleModel: "Huidig zadelmodel", tireWidthFrontMm: "Bandbreedte voor", tireWidthRearMm: "Bandbreedte achter", rimType: "Velgtype", surface: "Ondergrond", outerChainringTeeth: "Groot kettingblad", innerChainringTeeth: "Klein kettingblad", cassetteSmallestCogTeeth: "Kleinste krans", cassetteLargestCogTeeth: "Grootste krans" },
  calculators: { "bike-fit": "Bike-fitcalculator", "saddle-height": "Zadelhoogte-calculator", "frame-size": "Framemaat-calculator", "crank-length": "Cranklengte-calculator", "saddle-width": "Zadelbreedte-calculator", "tire-pressure": "Bandenspanning-calculator", gearing: "Versnellingen-calculator", "power-speed": "Vermogen-calculator", "climb-planner": "Klimplanner", "ftp-wkg": "FTP / W/kg-calculator", "fuel-hydration": "Voeding-calculator" },
  values: { very_limited: "Zeer beperkt", limited: "Beperkt", average: "Gemiddeld", good: "Goed", excellent: "Uitstekend", comfort: "Comfort", balanced: "Gebalanceerd", performance: "Prestatie", road: "Racefiets", gravel: "Gravelbike", mountain: "Mountainbike", mtb: "Mountainbike", hybrid: "Hybride", tt_triathlon: "Tijdrit / triatlon", tt: "Tijdrit", triathlon: "Triatlon", cyclocross: "Cyclocross", touring: "Toerfiets", city: "Stadsfiets", hooked: "Met haak", hookless: "Haakloos", unknown: "Onbekend", smooth: "Glad", average_road: "Gemiddeld wegdek", rough: "Ruw", road_smooth: "Glad asfalt", road_average: "Gemiddeld asfalt", road_rough: "Ruw asfalt", gravel_smooth: "Fijn gravel", gravel_rough: "Grof gravel", trail: "Bospad", low: "Laag", moderate: "Gemiddeld", high: "Hoog", heavy: "Veel", light: "Weinig", normal: "Normaal", ramp: "Ramptest", "20min": "20-minutentest", "60min": "60-minutentest", estimated: "Geschat", lab: "Laboratoriumtest" },
};

type Copy = { [Key in keyof typeof nl]: typeof nl[Key] extends string ? string : { [Nested in keyof typeof nl[Key]]: string } };

const en: Copy = {
  welcome: "Welcome", title: "Here’s what we’ll bring along", step: "Step 1 of 2 · your account is ready",
  intro: "From the calculators you just used. Choose which details go into your profile; you can change everything later.",
  rider: "Into your rider profile", riderHint: "about you, for every bike", bike: "Into a new bike profile", bikeHint: "only for this bike",
  keep: "Keep", omit: "Omit", adjust: "Adjust", createBike: "Create bike profile", later: "Later", bikeName: "Your bike’s name", bikeType: "Bike type", choose: "Choose an option",
  measurePoint: "Saddle height measurement point", measurePointOption: "Bottom bracket centre to saddle top", measurePointHint: "Confirm how you measured your current saddle height before saving it.",
  confirm: "Save and go to my dashboard", cancel: "Bring nothing, start empty", loading: "Loading your details…", saving: "Saving details…",
  empty: "There are no calculator details waiting. You can continue and fill in your profile later.", error: "We couldn’t save your details. They are still waiting here. Check your entries and try again.",
  conflict: "Your profile already has a different value", profileValue: "Your profile", incomingValue: "Today", profile: "From my profile", today: "From today", remeasure: "I’ll measure again", remeasureHint: "Your current profile value stays in place. Measure again and update your profile later.",
  start: "Your starting point", riderScore: "Rider profile", bikeScore: "Bike profile", scoreHint: "Every detail you add makes your advice more personal. We’ll ask at most two questions each visit.",
  first: "First question", gain: "+8 complete", question: "How far can you reach with straight legs?", flexHint: "Your drop advice takes your flexibility into account. You can skip this question.", flexKept: "Ready to save as self-assessed. Confirm your details below.",
  methods: { measured: "Measured", estimated: "Estimated", declared: "Provided", bike: "Bike detail" },
  extraValues: { known: "I know my FTP", twentyMinute: "Twenty-minute test", medium: "Average", smooth_asphalt: "Smooth asphalt", average_asphalt: "Average asphalt", rough_asphalt: "Rough asphalt", hardpack_gravel: "Hardpack gravel", loose_gravel: "Loose gravel" },
  fields: { heightCm: "Body height", inseamCm: "Inseam", flexibilityScore: "Flexibility", coreStabilityScore: "Core stability", ridingGoal: "Default riding goal", weightKg: "Weight", ftpWatts: "FTP", ftpMethod: "FTP method", sitBoneWidthMm: "Sit bone width", sweatProfile: "Sweat profile", bikeCategory: "Bike type", currentSaddleHeightMm: "Current saddle height", currentCrankLengthMm: "Current crank length", currentSaddleWidthMm: "Current saddle width", currentSaddleModel: "Current saddle model", tireWidthFrontMm: "Front tire width", tireWidthRearMm: "Rear tire width", rimType: "Rim type", surface: "Surface", outerChainringTeeth: "Outer chainring", innerChainringTeeth: "Inner chainring", cassetteSmallestCogTeeth: "Smallest cog", cassetteLargestCogTeeth: "Largest cog" },
  calculators: { "bike-fit": "Bike fit calculator", "saddle-height": "Saddle height calculator", "frame-size": "Frame size calculator", "crank-length": "Crank length calculator", "saddle-width": "Saddle width calculator", "tire-pressure": "Tire pressure calculator", gearing: "Gearing calculator", "power-speed": "Power calculator", "climb-planner": "Climb planner", "ftp-wkg": "FTP / W/kg calculator", "fuel-hydration": "Fuel calculator" },
  values: { very_limited: "Very limited", limited: "Limited", average: "Average", good: "Good", excellent: "Excellent", comfort: "Comfort", balanced: "Balanced", performance: "Performance", road: "Road bike", gravel: "Gravel bike", mountain: "Mountain bike", mtb: "Mountain bike", hybrid: "Hybrid", tt_triathlon: "Time trial / triathlon", tt: "Time trial", triathlon: "Triathlon", cyclocross: "Cyclocross", touring: "Touring", city: "City bike", hooked: "Hooked", hookless: "Hookless", unknown: "Unknown", smooth: "Smooth", average_road: "Average road", rough: "Rough", road_smooth: "Smooth asphalt", road_average: "Average asphalt", road_rough: "Rough asphalt", gravel_smooth: "Smooth gravel", gravel_rough: "Rough gravel", trail: "Trail", low: "Low", moderate: "Moderate", high: "High", heavy: "Heavy", light: "Light", normal: "Normal", ramp: "Ramp test", "20min": "20-minute test", "60min": "60-minute test", estimated: "Estimated", lab: "Lab test" },
};

export function getWelcomeCopy(locale: Locale): Copy { return locale === "nl" ? nl : en; }
