/** Generated by scripts/guides-batch-c/export.mjs from the bilingual editorial source. */
export const guideRewriteTitlesC: Readonly<Record<string, { nl: string; en: string }>> = {
  "bike-size-and-geometry": {
    "nl": "Fietsmaat en geometrie",
    "en": "Bike size and geometry"
  },
  "crank-length-guide": {
    "nl": "Cranklengte kiezen",
    "en": "Crank length"
  },
  "fit-science": {
    "nl": "Wetenschap achter bikefitting",
    "en": "Bike fitting science"
  },
  "gravel-bike-fit-guide": {
    "nl": "Gravelbike afstellen",
    "en": "Gravel bike fit"
  },
  "bike-fit-for-hand-numbness-and-wrist-pain": {
    "nl": "Gevoelloze handen fietsen: waar begin je?",
    "en": "Numb hands cycling: where should you start?"
  },
  "hydration-and-sweat-rate-guide": {
    "nl": "Zweetverlies meten fietsen",
    "en": "Cycling sweat rate"
  },
  "nutrition-and-hydration": {
    "nl": "Voeding en drinken wielrennen",
    "en": "Cycling nutrition and hydration"
  },
  "when-online-bike-fit-has-limits": {
    "nl": "Wanneer professionele bikefit",
    "en": "Online bike fit limitations"
  },
  "road-vs-endurance-vs-race-geometry": {
    "nl": "Racefiets of endurancegeometrie",
    "en": "Race versus endurance geometry"
  },
  "reach-and-stem-guide": {
    "nl": "Stuurpenlengte bepalen",
    "en": "Stem length"
  },
  "bike-fit-for-saddle-pressure-perineal-numbness-and-saddle-sores": {
    "nl": "Zadelpijn fietsen: steun, druk en wrijving",
    "en": "Saddle pain cycling: support, pressure and friction"
  },
  "shoe-foot-cleat-fit": {
    "nl": "Fietsschoenen en schoenplaatjes afstellen",
    "en": "Cycling shoe and cleat fit"
  }
};
