/** Generated by scripts/guides-batch-d/export.mjs from the bilingual editorial source. */
export const guideRewriteTitlesD: Readonly<Record<string, { nl: string; en: string }>> = {
  "bike-fit-for-neck-and-shoulder-pain": {
    "nl": "Nekpijn fietsen: ontspan je schouders",
    "en": "Neck pain cycling: relax your shoulders"
  },
  "bike-fit-for-tall-riders": {
    "nl": "Fiets afstellen lange fietsers: waar begin je?",
    "en": "Bike fit tall riders: where to start"
  },
  "carbs-per-hour-guide": {
    "nl": "Koolhydraten per uur fietsen: maak je plan",
    "en": "Carbs per hour cycling: make your plan"
  },
  "cycling-fueling-basics": {
    "nl": "Eten tijdens fietsen: maak een werkbaar plan",
    "en": "Cycling fueling basics: build a practical plan"
  },
  "foot-measurement-guide-for-cyclists": {
    "nl": "Voet opmeten fietsschoenen: lengte en breedte",
    "en": "Foot measurement cycling: length and width"
  },
  "handlebar-drop-guide": {
    "nl": "Stuurhoogte racefiets: vind je drop",
    "en": "Handlebar drop: find your bar height"
  },
  "indoor-trainer-bike-fit-guide": {
    "nl": "Fiets afstellen indoortrainer",
    "en": "Indoor trainer bike fit"
  },
  "pain-and-discomfort": {
    "nl": "Pijn bij fietsen: kies je eerste stap",
    "en": "Cycling pain: choose your first step"
  },
  "ride-types": {
    "nl": "Fiets afstellen per fietstype",
    "en": "Bike fit riding styles"
  },
  "saddle-fore-aft-and-tilt-guide": {
    "nl": "Zadel terugstand en kanteling afstellen",
    "en": "Saddle setback and tilt adjustment"
  },
  "sodium-and-electrolytes-guide": {
    "nl": "Natrium sportdrank fietsen: lees de concentratie",
    "en": "Sodium cycling drink: read the concentration"
  },
  "wkg-and-power-zones-guide": {
    "nl": "Watt per kilo fietsen: begrijp je getal",
    "en": "Cycling watts per kilogram: understand the number"
  }
};
