export const BRAND = {
  name: "BestBikeFit4U",
  legacyName: "BikeFit AI",
  siteUrl: "https://bestbikefit4u.eu",
  host: "bestbikefit4u.eu",
  authEmailFrom: "BestBikeFit4U <noreply@notifications.bestbikefit4u.eu>",
  supportEmail: "support@bestbikefit4u.eu",
  reportTitle: "BestBikeFit4U - Fit Recommendation Report",
  reportSlug: "bestbikefit4u-report",
  assets: {
    logoPrimary: "/brand/logo/logo-horizontaal.svg",
    logoDark: "/brand/logo/logo-horizontaal-negatief.svg",
    mark: "/brand/logo/beeldmerk.svg",
    appIconSvg: "/brand/favicon/favicon.svg",
    appleTouchIcon: "/brand/favicon/apple-touch-icon.png",
    appIcon192: "/brand/favicon/android-chrome-192.png",
    appIconMaskable: "/brand/favicon/maskable-512.png",
    favicon: "/brand/favicon/favicon.ico",
    socialImage: "/brand/social/og-image-1200x630.png",
    appIconPng: "/brand/favicon/android-chrome-512.png",
  },
} as const;
